# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nucleo.jor.br
title: Núcleo Jornalismo
email: nucleo@voltdata.info
author: Núcleo Jornalismo
description: > # "Write an awesome description for your new site here.
  Núcleo é um site de jornalismo que busca trazer transparência para informações, debates e políticas públicas, sempre utilizando dados e códigos abertos
copyright: 'Copyright &copy; 2018 Volt Data Lab. Todos os direitos reservados.'
credits: 'Página construída em Jekyll por Sérgio Spagnuolo.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/nucleojornalismo
  - title: facebook
    url: https://facebook.com/Nucleojornalismo
  - title: github
    url: https://github.com/voltdatalab
