# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nucleo.jor.br/ #
baseurl: #
title: Núcleo Jornalismo
email: nucleo@voltdata.info
author: Núcleo Jornalismo
description: > # "Write an awesome description for your new site here.
  Núcleo é um site de jornalismo que busca trazer transparência para informações, debates e políticas públicas, sempre com dados e códigos abertos
copyright: '<img src="img/landing-nucleo_logo+tagline.png" width="200px" />'
credits: 'Copyright © 2020 | Volt Data Lab. Todos os direitos reservados. Este site utiliza apenas Google Analytics para monitorar os acessos.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/nucleojor
  - title: facebook
    url: https://www.facebook.com/Nucleojornalismo-111261027051278
  - title: github
    url: https://github.com/voltdatalab
