# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nucleo.jor.br/ #
baseurl: #
title: Núcleo Jornalismo
email: nucleo@voltdata.info
author: Núcleo Jornalismo
description: > # "Write an awesome description for your new site here.
  Investigações sobre debates, gastos públicos e políticas públicas
copyright: '<img src="{{site.baseurl}}/img/landing-nucleo_logo+tagline.png" width="200px" />'
credits: 'Copyright © 2020 | Volt Data Lab. Todos os direitos reservados. Reprodução integral do conteúdo deste site depende de aprovação, mas citações e reprodução parcial, com links para origem, são permitidas e apreciadas. Este site utiliza apenas Google Analytics.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: /:categories/:year-:month-:day-:title

paginate:           5
paginate_path:      "/posts/page:num/"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/nucleojor
  - title: facebook
    url: https://www.facebook.com/Nucleojor-103656567831757
  - title: github
    url: https://github.com/voltdatalab
  - title: whatsapp
    url: https://wa.me/5511934441844

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
